#!/usr/bin/env python3
"""Write dev/glance.generated.yml (or $CONFIG_OUT, port $GLANCE_PORT): a Glance page with three variants of the widget.

  small column : default options                      (id: ma)
  full column  : big-cover: true                      (id: ma-big)
                 show-controls: false, read-only      (id: ma-ro)

Glance's $include cannot override options, so the variants are made by
replacing option lines in widget/music-assistant.yml.
"""

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIDGET = (ROOT / "widget" / "music-assistant.yml").read_text(encoding="utf-8")


def variant(replacements: dict[str, str], indent: str) -> str:
    text = WIDGET
    for old, new in replacements.items():
        if old not in text:
            raise SystemExit(f"option line not found in widget file: {old!r}")
        text = text.replace(old, new, 1)
    return "".join(indent + line if line.strip() else line for line in text.splitlines(keepends=True))


INDENT = " " * 10
config = f"""# Generated by dev/make_config.py, do not edit
server:
  host: 127.0.0.1
  port: {os.environ.get("GLANCE_PORT", "8080")}

pages:
  - name: Home
    columns:
      - size: small
        widgets:
{variant({}, INDENT)}
      - size: full
        widgets:
{variant({"id: ma ": "id: ma-big ", "big-cover: false": "big-cover: true", "queue-length: 4 ": "queue-length: 3 "}, INDENT)}
{variant({"id: ma ": "id: ma-ro ", "show-controls: true ": "show-controls: false", "title: Music Assistant": "title: Read-only"}, INDENT)}
"""

out = Path(os.environ.get("CONFIG_OUT", ROOT / "dev" / "glance.generated.yml"))
out.write_text(config, encoding="utf-8")
print(f"wrote {out}")
